import React from 'react';
import { View, StyleSheet, ScrollView, Pressable } from 'react-native';
import { Text } from '../components/Typography';
import { majors } from '../data/majors';
import { Major } from '../types';
import { MajorCard } from '../components/MajorCard';
type Props = { savedIds: string[]; onToggleSave: (major: Major) => void; onExplore: () => void };
export function SavedScreen({ savedIds, onToggleSave, onExplore }: Props) { const saved = majors.filter((major) => savedIds.includes(major.id)); return <ScrollView style={styles.container} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>YOUR SHORTLIST</Text><Text style={styles.title}>Saved majors</Text><Text style={styles.subtitle}>{saved.length ? `${saved.length} path${saved.length === 1 ? '' : 's'} saved for later.` : 'Keep the majors you want to come back to in one place.'}</Text>{saved.length ? saved.map((major) => <MajorCard key={major.id} major={major} onPress={() => {}} onToggleSave={() => onToggleSave(major)} saved />) : <View style={styles.empty}><View style={styles.emptyMark}><Text style={styles.emptyMarkText}>+</Text></View><Text style={styles.emptyTitle}>Your list is open</Text><Text style={styles.emptyText}>Save majors as you explore to build your personal shortlist.</Text><Pressable style={styles.button} onPress={onExplore}><Text style={styles.buttonText}>Explore majors</Text></Pressable></View>}</ScrollView>; }
const styles = StyleSheet.create({ container: { backgroundColor: '#F6F7FB' }, content: { padding: 20, paddingBottom: 32 }, eyebrow: { color: '#63708F', fontSize: 10, fontWeight: '800', letterSpacing: 1.2, marginBottom: 5 }, title: { fontSize: 28, color: '#182343', fontWeight: '800', marginBottom: 6 }, subtitle: { color: '#667188', fontSize: 15, lineHeight: 22, marginBottom: 24 }, empty: { alignItems: 'center', backgroundColor: '#FFF', borderRadius: 20, padding: 28, borderWidth: 1, borderColor: '#E7EAF2' }, emptyMark: { width: 50, height: 50, borderRadius: 25, backgroundColor: '#E7EAFF', alignItems: 'center', justifyContent: 'center', marginBottom: 14 }, emptyMarkText: { color: '#4056C6', fontSize: 28, fontWeight: '500' }, emptyTitle: { color: '#263250', fontSize: 18, fontWeight: '800', marginBottom: 7 }, emptyText: { color: '#707A91', textAlign: 'center', lineHeight: 21 }, button: { backgroundColor: '#4056C6', borderRadius: 12, marginTop: 20, paddingVertical: 12, paddingHorizontal: 16 }, buttonText: { color: '#FFF', fontWeight: '800' } });
