import React from 'react';
import { View, Pressable, StyleSheet } from 'react-native';
import { Text } from './Typography';
import { Major } from '../types';
import { darkModeAccent, useTheme } from '../lib/theme';

type Props = { major: Major; onPress: () => void; onToggleSave: () => void; saved: boolean };

export function MajorCard({ major, onPress, onToggleSave, saved }: Props) {
  const { isDark } = useTheme();
  const categoryColor = isDark ? darkModeAccent(major.color) : major.color;
  return <Pressable style={({ pressed }) => [styles.card, isDark && dark.card, { borderColor: major.color + (isDark ? 'B8' : '78'), shadowColor: major.color }, pressed && styles.cardPressed]} onPress={onPress}><View style={styles.cardTop}><View style={[styles.badge, { backgroundColor: major.color + (isDark ? '32' : '20'), borderColor: major.color + '66' }, isDark && styles.badgeDark]}><Text style={[styles.badgeText, { color: categoryColor }]}>{major.category}</Text></View><Pressable hitSlop={8} style={[styles.saveButton, isDark && dark.button, saved && styles.saveButtonActive, isDark && saved && dark.savedButton]} onPress={onToggleSave}><Text style={[styles.saveText, isDark && dark.muted, saved && styles.saveTextActive, isDark && saved && dark.savedText]}>{saved ? 'Saved' : 'Save'}</Text></Pressable></View><Text style={[styles.title, isDark && dark.text]}>{major.title}</Text><Text style={[styles.subtitle, isDark && dark.muted]}>{major.subtitle}</Text><View style={[styles.detailsRow, isDark && dark.border]}><View><Text style={[styles.detailCaption, isDark && dark.caption]}>DIFFICULTY</Text><Text style={[styles.detailValue, isDark && dark.text]}>{major.difficulty}</Text></View><View><Text style={[styles.detailCaption, isDark && dark.caption]}>MEDIAN PAY</Text><Text style={[styles.detailValue, isDark && dark.text]}>{major.salary}</Text></View></View></Pressable>;
}

const styles = StyleSheet.create({ card: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 17, marginBottom: 12, borderWidth: 1.5, shadowOpacity: .12, shadowRadius: 9, shadowOffset: { width: 0, height: 4 }, elevation: 2 }, cardPressed: { opacity: .92, transform: [{ scale: .992 }] }, cardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }, badge: { alignSelf: 'flex-start', borderRadius: 99, paddingVertical: 6, paddingHorizontal: 10 }, badgeDark: { borderWidth: 1 }, badgeText: { fontSize: 12, fontWeight: '800' }, saveButton: { borderRadius: 10, paddingVertical: 7, paddingHorizontal: 10, backgroundColor: '#F0F2F7' }, saveButtonActive: { backgroundColor: '#E7EAFF' }, saveText: { color: '#59657C', fontWeight: '800', fontSize: 12 }, saveTextActive: { color: '#4056C6' }, title: { color: '#233050', fontSize: 18, fontWeight: '800', marginBottom: 6 }, subtitle: { fontSize: 14, color: '#6F7990', marginBottom: 15, lineHeight: 20 }, detailsRow: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: '#EEF0F5', paddingTop: 12, gap: 36 }, detailCaption: { color: '#9AA2B2', fontSize: 10, fontWeight: '800', letterSpacing: .6, marginBottom: 4 }, detailValue: { color: '#3D4961', fontWeight: '800', fontSize: 13 } });
const dark = StyleSheet.create({ card: { backgroundColor: '#131B2D', borderColor: '#2A3852' }, button: { backgroundColor: '#202B42' }, savedButton: { backgroundColor: '#27345D' }, savedText: { color: '#B8C0FF' }, text: { color: '#F4F7FC' }, muted: { color: '#A7B2C7' }, caption: { color: '#8998B5' }, border: { borderTopColor: '#2A3852' } });
